name: benchmark_gnn
channels:
- pytorch 
- dglteam/label/th24_cu124
- conda-forge
- fragcolor
- anaconda
- defaults
dependencies:
- git
- pip
- python=3.9
- pytorch=2.4.0
- pydantic>=2.0
- torchvision
- torchaudio
- numpy
- matplotlib
- tensorboard
- tensorboardx
- scikit-learn
- scipy
- notebook
- ipykernel
- ipython
- jupyter
- plotly
- pandas
- dill
- ogb
- dgl
- pip:
  - tensorflow
  - dill